const About = () => {
    return (
        <div>
            <h1>Why CoinCrowd?</h1>
            <p>
                If you weren't a part of Reddit's WallStreetBets community in 2019, you probably missed out on buying GameStop stock for only a few dollars before its astronomical run-up.
                If you didn't actively browse the Business and Finance board on 4chan in 2020-2021, you certainly missed out on buying $SHIB when its marketcap was well under $1 million (its current valuation is $7 billion, with an all-time high valuation of $41 billion).
                
                Clearly, then, the best way to amass enormous wealth quickly is to scour obscure online communities until you find the perfect "gem": a completely unknown deep-value play that emerges out of the internet's left field, a one-way ticket to generational wealth.
                But how many hours do you have in your day? How many of them can you reasonably spend online? How long would it take you to decipher any particular community's odd colloquialisms and lingo? More importantly, how can you possibly know what you don't know? There are countless discussion forums, message boards, and group chats out in the virtual ether; how can you possibly expect to keep tabs on them all, particularly the ones whose existence you aren't aware of? Most importantly, what if these online would-be Michael Burry's end up being wrong on the day you decide to do as they say? How could you reasonably and expediently tell if an online group of investment nerds has any clue what they're talking about?
            </p>

            <h1>A Solution to Information Asymmetry</h1>
            <p>
                It may be disheartening for one to realize that the only difference between them and someone who made millions from a single stock purchase is that they weren't in the right place at the right time.
                Not only does it eat away at our notions of meritocracy, it presents an immense logistical problem for those who wish to maximize the value of their time.
                Thankfully, we have technology that can distribute the benefits of happenstance more equitably.
                CoinCrowd uses NLP models trained on posts from financial discussion communities that identify any financial assets being discussed. This can be used to gauge an asset's popularity in the community by tracking mention frequency over time. In the future, models will be trained to assess the community's sentiment about these assets, which will also be tracked over time.
                The data generated by these fairly simple machine learning techniques are compared against an asset's price. Several valuable insights can be derived by this comparison:
            </p>
            <ul>
                <li>If a particular community (for example, Reddit, which may represent discussion from several finance-focused subreddits) shows consistent spikes in popularity and sentiment that precede increases in asset prices, that community can be deemed "accurate" in predicting an asset's price.</li>
                <li></li>
            </ul>
            <h1>Why not GPT?</h1>
            <p>GPT is a generative model that's designed to output novel text in response to input text. Conversationally prompting it to analyze a chunk of text is interesting but wildly inefficient.</p>
            <p>OpenAI offers the use of some NLP models as a per-token service, but this becomes prohibitively expensive at scale for anyone who isn't an established firm with plenty of cash to spare. Additionally, these generalized language models tend to fail when faced with lingo it hasn't been trained on (it's doubtful that DAVINCI understands the sentiment conveyed by the phrase "BITFUCK IS GOING TO ZERO!", for example).</p>

        </div>
    )
}

export default About